development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://aknmlqdnbnsbvr:bffb6638a0ab92145f0a377b671a280f34787ef18a82bad6f1affbbfba3d0dd1@ec2-54-83-204-230.compute-1.amazonaws.com:5432/d2g1fbngced26h
  # channel_prefix: nameofapp_production
